import { Images } from "./images";

const DUMMY_PRODUCTS = [
  {
    id: 1,
    band: "Avenged Sevenfold",
    album: "Sounding the Seventh Trumpet",
    genre: "Metal",
    releaseDate: 2001,
    price: 9.99,
    image: Images.image1,
    tracklist: [
      "To End the Rapture",
      "Turn the Other Way",
      "Darkness Surrounding",
      "The Art of Subconscious Illusion",
      "We Come Out at Night",
      "Lips of Deceit",
      "Warmness on the Soul",
      "An Epic of Time Wasted",
      "Breaking Their Hold",
      "Forgotten Faces",
      "Thick and Thin",
      "Streets",
      "Shattered by Broken Dreams",
    ],
  },
  {
    id: 2,
    band: "Avenged Sevenfold",
    album: "Waking the Fallen",
    genre: "Metal",
    releaseDate: 2003,
    price: 11.99,
    image: Images.image2,
    tracklist: [
      "Waking the Fallen",
      "Unholy Confessions",
      "Chapter Four",
      "Remenissions",
      "Desecrate Through Reverance",
      "Eternal Rest",
      "Second Heartbeat",
      "Radiant Eclipse",
      "I Won't See You Tonight (Part 1)",
      "I Won't See You Tonight (Part 2)",
      "Clairvoyant Disease",
      "And All Things Will End",
    ],
  },
  {
    id: 3,
    band: "Avenged Sevenfold",
    album: "City of Evil",
    genre: "Metal",
    releaseDate: 2005,
    price: 15.99,
    image: Images.image3,
    tracklist: [
      "Beast and the Harlot",
      "Burn It Down",
      "Blinded in Chains",
      "Bat Country",
      "Trashed and Scattered",
      "Seize the Day",
      "Sidewinder",
      "The Wicked End",
      "Strength of the World",
      "Betrayed",
      "M.I.A.",
    ],
  },
  {
    id: 4,
    band: "Avenged Sevenfold",
    album: "Avenged Sevenfold",
    genre: "Metal",
    releaseDate: 2007,
    price: 14.99,
    image: Images.image4,
    tracklist: [
      "Critical Acclaim",
      "Almost Easy",
      "Scream",
      "Afterlife",
      "Gunslinger",
      "Unbound (The Wild Ride)",
      "Brompton Cocktail",
      "Lost",
      "A Little Piece of Heaven",
      "Dear God",
    ],
  },
  {
    id: 5,
    band: "Avenged Sevenfold",
    album: "Nightmare",
    genre: "Metal",
    releaseDate: 2010,
    price: 13.99,
    image: Images.image5,
    tracklist: [
      "Nightmare",
      "Welcome to the Family",
      "Danger Line",
      "Buried Alive",
      "Natural Born Killer",
      "So Far Away",
      "God Hates Us",
      "Victim",
      "Tonight the World Dies",
      "Fiction",
      "Save Me",
    ],
  },
  {
    id: 6,
    band: "Avenged Sevenfold",
    album: "Hail to the King",
    genre: "Metal",
    releaseDate: 2013,
    price: 12.99,
    image: Images.image6,
    tracklist: [
      "Shepherd of Fire",
      "Hail to the King",
      "Doing Time",
      "This Means War",
      "Requiem",
      "Crimson Day",
      "Heretic",
      "Coming Home",
      "Planets",
      "Acid Rain",
    ],
  },
  {
    id: 7,
    band: "Avenged Sevenfold",
    album: "The Stage",
    genre: "Metal",
    releaseDate: 2016,
    price: 12.99,
    image: Images.image7,
    tracklist: [
      "The Stage",
      "Paradigm",
      "Sunny Disposition",
      "God Damn",
      "Creating God",
      "Angels",
      "Simulation",
      "Higher",
      "Roman Sky",
      "Fermi Paradox",
      "Exist",
    ],
  },
  {
    id: 8,
    band: "The Weeknd",
    album: "Trilogy",
    genre: "R&B",
    releaseDate: 2012,
    price: 14.99,
    image: Images.image8,
    tracklist: [
      "High for This",
      "What You Need",
      "House of Balloons / Glass Table Girls",
      "The Morning",
      "Wicked Games",
      "The Party & the After Party",
      "Coming Down",
      "Loft Music",
      "The Knowing",
      "Twenty Eight",
      "Lonely Star",
      "Life of the Party",
      "Thursday",
      "The Zone (feat. Drake)",
      "The Birds, Pt. 1",
      "The Birds, Pt. 2",
      "Gone",
      "Rolling Stone",
      "Heaven or Las Vegas",
      "Valerie",
      "D.D.",
      "Montreal",
      "Outside",
      "XO / The Host",
      "Initiation",
      "Same Old Song (feat. Juicy J)",
      "The Fall",
      "Next",
      "Echoes of Silence",
      "Till Dawn (Here Comes the Sun)",
      "The Zone (feat. Drake) [Alternate Version]",
      "Montreal (Alternate Version)",
    ],
  },
  {
    id: 9,
    band: "The Weeknd",
    album: "Kiss Land",
    genre: "R&B",
    releaseDate: 2013,
    price: 9.99,
    image: Images.image9,
    tracklist: [
      "Professional",
      "The Town",
      "Adaptation",
      "Love in the Sky",
      "Belong to the World",
      "Live For",
      "Wanderlust",
      "Kiss Land",
      "Pretty",
      "Tears in the Rain",
    ],
  },
  {
    id: 10,
    band: "The Weeknd",
    album: "Beauty Behind the Madness",
    genre: "R&B",
    releaseDate: 2015,
    price: 12.99,
    image: Images.image10,
    tracklist: [
      "Real Life",
      "Losers",
      "Tell Your Friends",
      "Often",
      "The Hills",
      "Acquainted",
      "Can't Feel My Face",
      "Shameless",
      "Earned It (Fifty Shades of Grey)",
      "In the Night",
      "As You Are",
      "Dark Times",
      "Prisoner",
      "Angel",
    ],
  },
  {
    id: 11,
    band: "The Weeknd",
    album: "Starboy",
    genre: "R&B",
    releaseDate: 2016,
    price: 11.99,
    image: Images.image11,
    tracklist: [
      "Starboy",
      "Party Monster",
      "False Alarm",
      "Reminder",
      "Rockin'",
      "Secrets",
      "True Colors",
      "Stargirl Interlude",
      "Sidewalks",
      "Six Feet Under",
      "Love to Lay",
      "A Lonely Night",
      "Attention",
      "Ordinary Life",
      "Nothing Without You",
      "All I Know",
      "Die For You",
      "I Feel It Coming",
    ],
  },
  {
    id: 12,
    band: "The Weeknd",
    album: "My Dear Melancholy",
    genre: "R&B",
    releaseDate: 2018,
    price: 7.99,
    image: Images.image12,
    tracklist: [
      "Call Out My Name",
      "Try Me",
      "Wasted Times",
      "I Was Never There",
      "Hurt You",
      "Privilege",
    ],
  },
  {
    id: 13,
    band: "The Weeknd",
    album: "After Hours",
    genre: "R&B",
    releaseDate: 2020,
    price: 12.99,
    image: Images.image13,
    tracklist: [
      "Alone Again",
      "Too Late",
      "Hardest to Love",
      "Scared to Live",
      "Snowchild",
      "Escape from LA",
      "Heartless",
      "Faith",
      "Blinding Lights",
      "In Your Eyes",
      "Save Your Tears",
      "Repeat After Me (Interlude)",
      "After Hours",
      "Until I Bleed Out",
    ],
  },
  {
    id: 14,
    band: "Billie Eilish",
    album: "When We All Fall Asleep, Where Do We Go?",
    genre: "Pop",
    releaseDate: 2019,
    price: 10.99,
    image: Images.image14,
    tracklist: [
      "!!!!!!!",
      "Bad Guy",
      "Xanny",
      "You Should See Me in a Crown",
      "All the Good Girls Go to Hell",
      "Wish You Were Gay",
      "When the Party's Over",
      "8",
      "My Strange Addiction",
      "Bury a Friend",
      "Ilomilo",
      "Listen Before I Go",
      "I Love You",
      "Goodbye",
    ],
  },
  {
    id: 15,
    band: "Billie Eilish",
    album: "Happier Than Ever",
    genre: "Pop",
    releaseDate: 2021,
    price: 11.99,
    image: Images.image15,
    tracklist: [
      "Getting Older",
      "I Didn't Change My Number",
      "Billie Bossa Nova",
      "my future",
      "Oxytocin",
      "Goldwing",
      "Lost Cause",
      "Halley's Comet",
      "Not My Responsibility",
      "OverHeated",
      "Everybody Dies",
      "Your Power",
      "NDA",
      "Therefore I Am",
      "Happier Than Ever",
      "Male Fantasy",
    ],
  },
  {
    id: 16,
    band: "Ariana Grande",
    album: "Yours Truly",
    genre: "Pop",
    releaseDate: 2013,
    price: 9.99,
    image: Images.image16,
    tracklist: [
      "Honeymoon Avenue",
      "Baby I",
      "Right There (feat. Big Sean)",
      "Tattooed Heart",
      "Lovin' It",
      "Piano",
      "Daydreamin'",
      "The Way (feat. Mac Miller)",
      "You'll Never Know",
      "Almost Is Never Enough (feat. Nathan Sykes)",
      "Popular Song (feat. MIKA)",
      "Better Left Unsaid",
    ],
  },
  {
    id: 17,
    band: "Ariana Grande",
    album: "My Everything",
    genre: "Pop",
    releaseDate: 2014,
    price: 11.99,
    image: Images.image17,
    tracklist: [
      "Intro",
      "Problem (feat. Iggy Azalea)",
      "One Last Time",
      "Why Try",
      "Break Free (feat. Zedd)",
      "Best Mistake (feat. Big Sean)",
      "Be My Baby (feat. Cashmere Cat)",
      "Break Your Heart Right Back (feat. Childish Gambino)",
      "Love Me Harder (with The Weeknd)",
      "Just a Little Bit of Your Heart",
      "Hands on Me (feat. A$AP Ferg)",
      "My Everything",
      "Bang Bang",
      "Only 1",
      "You Don't Know Me",
    ],
  },
  {
    id: 18,
    band: "Ariana Grande",
    album: "Dangerous Woman",
    genre: "Pop",
    releaseDate: 2016,
    price: 10.99,
    image: Images.image18,
    tracklist: [
      "Moonlight",
      "Dangerous Woman",
      "Be Alright",
      "Into You",
      "Side to Side (feat. Nicki Minaj)",
      "Let Me Love You (feat. Lil Wayne)",
      "Greedy",
      "Leave Me Lonely (feat. Macy Gray)",
      "Everyday (feat. Future)",
      "Sometimes",
      "I Don't Care",
      "Bad Decisions",
      "Touch It",
      "Knew Better / Forever Boy",
      "Thinking Bout You",
    ],
  },
  {
    id: 19,
    band: "Ariana Grande",
    album: "Sweetener",
    genre: "Pop",
    releaseDate: 2018,
    price: 12.99,
    image: Images.image19,
    tracklist: [
      "raindrops (an angel cried)",
      "blazed (feat. Pharrell Williams)",
      "the light is coming (feat. Nicki Minaj)",
      "R.E.M.",
      "God is a woman",
      "sweetener",
      "successful",
      "everytime",
      "breathin",
      "no tears left to cry",
      "borderline (feat. Missy Elliott)",
      "better off",
      "goodnight n go",
      "pete davidson",
      "get well soon",
    ],
  },
  {
    id: 20,
    band: "Ariana Grande",
    album: "thank u, next",
    genre: "Pop",
    releaseDate: 2019,
    price: 10.99,
    image: Images.image20,
    tracklist: [
      "imagine",
      "needy",
      "NASA",
      "bloodline",
      "fake smile",
      "bad idea",
      "make up",
      "ghostin",
      "in my head",
      "7 rings",
      "thank u, next",
      "break up with your girlfriend, i'm bored",
    ],
  },
  {
    id: 21,
    band: "Ariana Grande",
    album: "Positions",
    genre: "Pop",
    releaseDate: 2020,
    price: 11.99,
    image: Images.image21,
    tracklist: [
      "shut up",
      "34+35",
      "motive",
      "just like magic",
      "off the table",
      "six thirty",
      "safety net",
      "my hair",
      "nasty",
      "west side",
      "love language",
      "positions",
      "obvious",
      "pov",
    ],
  },
  {
    id: 22,
    band: "Bring Me the Horizon",
    album: "Sempiternal",
    genre: "Metal",
    releaseDate: 2013,
    price: 9.99,
    image: Images.image22,
    tracklist: [
      "Can You Feel My Heart",
      "The House of Wolves",
      "Empire (Let Them Sing)",
      "Sleepwalking",
      "Go to Hell, for Heaven's Sake",
      "Shadow Moses",
      "And the Snakes Start to Sing",
      "Seen It All Before",
      "Antivist",
      "Crooked Young",
      "Hospital for Souls",
    ],
  },
  {
    id: 23,
    band: "Bring Me the Horizon",
    album: "That's the Spirit",
    genre: "Metal",
    releaseDate: 2015,
    price: 11.99,
    image: Images.image23,
    tracklist: [
      "Doomed",
      "Happy Song",
      "Throne",
      "True Friends",
      "Follow You",
      "What You Need",
      "Avalanche",
      "Run",
      "Drown",
      "Blasphemy",
      "Oh No",
    ],
  },
  {
    id: 24,
    band: "Travis Scott",
    album: "Birds in the Trap Sing McKnight",
    genre: "Hip Hop",
    releaseDate: 2016,
    price: 10.99,
    image: Images.image24,
    tracklist: [
      "the ends",
      "way back",
      "coordinate",
      "through the late night",
      "beibs in the trap",
      "sdp interlude",
      "sweet sweet",
      "outside",
      "goosebumps",
      "first take",
      "pick up the phone",
      "lose",
      "guidance",
    ],
  },
  {
    id: 25,
    band: "Travis Scott",
    album: "Astroworld",
    genre: "Hip Hop",
    releaseDate: 2018,
    price: 12.99,
    image: Images.image25,
    tracklist: [
      "STARGAZING",
      "CAROUSEL",
      "SICKO MODE",
      "R.I.P. SCREW",
      "STOP TRYING TO BE GOD",
      "NO BYSTANDERS",
      "SKELETONS",
      "WAKE UP",
      "5% TINT",
      "NC-17",
      "ASTROTHUNDER",
      "YOSEMITE",
      "CAN'T SAY",
      "WHO? WHAT!",
      "BUTTERFLY EFFECT",
      "HOUSTONFORNICATION",
      "COFFEE BEAN",
    ],
  },
  {
    id: 26,
    band: "Harry Styles",
    album: "Harry Styles",
    genre: "Pop",
    releaseDate: 2017,
    price: 9.99,
    image: Images.image26,
    tracklist: [
      "Meet Me in the Hallway",
      "Sign of the Times",
      "Carolina",
      "Two Ghosts",
      "Sweet Creature",
      "Only Angel",
      "Kiwi",
      "Ever Since New York",
      "Woman",
      "From the Dining Table",
    ],
  },
  {
    id: 27,
    band: "Harry Styles",
    album: "Fine Line",
    genre: "Pop",
    releaseDate: 2019,
    price: 12.99,
    image: Images.image27,
    tracklist: [
      "Golden",
      "Watermelon Sugar",
      "Adore You",
      "Lights Up",
      "Cherry",
      "Falling",
      "To Be So Lonely",
      "She",
      "Sunflower, Vol. 6",
      "Canyon Moon",
      "Treat People with Kindness",
      "Fine Line",
    ],
  },
  {
    id: 28,
    band: "Harry Styles",
    album: "Harry's House",
    genre: "Pop",
    releaseDate: 2022,
    price: 13.99,
    image: Images.image28,
    tracklist: [
      "Music For a Sushi Restaurant",
      "Late Night Talking",
      "Grapejuice",
      "As It Was",
      "Daylight",
      "Little Freak",
      "Matilda",
      "Cinema",
      "Daydreaming",
      "Keep Driving",
      "Satellite",
      "Boyfriends",
      "Love Of My Life",
    ],
  },
];

export default DUMMY_PRODUCTS;
